image: maven:3-jdk-11-slim

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build

test:
  stage: test
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd HAPark
    - mvn clean test surefire-report:report
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      junit:
        - HAPark/target/surefire-reports/TEST-*.xml
  when: always

build:
  stage: build
  tags: 
    - dalfcs_docker_kvm
    - dalfcs_gitlab_docker_ci
  script:
    - cd HAPark
    - mvn package
  artifacts:
    paths:
      - HAPark/target/*.jar
  when: always